name: Deployment

on:
  workflow_run:
    workflows: [docker-image]
    types:
      - completed

jobs:
  dev-pipeline:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Repo
          uses: actions/checkout@v3.3.0

        - uses: hashicorp/setup-terraform@v2
          with:
            terraform_version: 1.4.1
            
        - name: Run Terraform
          run: |
              echo "cd into your terraform directory and run a terraform init and plan"
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
            AWS_DEFAULT_REGION: 'eu-west-1'
